### PR TITLE
Harr'qac activities expansion

### PR DESCRIPTION
**Pull request by samo-novak**
This branch is based on the early #96 Harr'qac branch, the first commit is common for both. 
That being said, #96 should be merged first, but it doesn't necessarily need to.

Expanded on:
* Infrastructure
* Energy
* Research activities
* Tourism

Should be pretty safe in terms of Skrellian lore. 

Again, use the rich diff to view the changes properly

### CODE REVIEW

**Comment by samo-novak** [comment]
Bump

**Comment by ParadoxonKomplikon** [comment]
Just popping in to say I reviewed and approved Superbee's changes II: Electric Boogaloo

**Comment by Spookerton** [comment]
Sorry @Superbee29 , squashmerge on #96 made this one unfriendly.

**Comment by samo-novak** [comment]
Resolved conflicts

**Pull request merged**
