### PR TITLE
Microlore Pt. 1: The Prologue

### PR DESCRIPTION
**Pull request by redstryker**

### CODE REVIEW

**Comment by ThatOneGuy42** [comment]
I would suggest adding an opening Paragraph to the Consumer Goods page to describe what the page is about, and what will be available on the page, as well as connecting a link to the "What Else Do You Wanna Know?" Page (Section-9.md in the git) because the closest thing to a Technology page there is is a Science page, and I don't think cigarettes microlore fits there, and the WEDYWK page would be far more fitting.

**Comment by redstryker** [comment]
@ThatOneGuy42 , fixed, along with some other things.

**Comment by Raptor1628** [comment]
We've got a mix up here, in the can's lore, it says Robust is the parent company, but in Centauri it says that Robust is the subsidiary.

**Comment by Raptor1628** [comment]
Progress on this?

**Comment by redstryker** [comment]
Been busy with school this week.  May fix tonight.  I will probably discuss it with you first.

**Pull request merged**
