### PR TITLE
Adds a page for the Prometheans.

### PR DESCRIPTION
**Pull request by tlc2013**
As noted in the commits themselves, this PR only adds the page itself; any further modifications to the wiki on this matter, such as linking to it in the Species list, should probably be reserved until the Prometheans themselves are fully reworked.

Heck, you could probably keep this entire PR on hold until then, if you wanted. I don't mind.

### CODE REVIEW

**Comment by ThatOneGuy42** [comment]
....Why does this need 12 commits?

**Comment by SiegDerMaus** [comment]
On hold until the Serpentids species is finished.

**Comment by tlc2013** [comment]
@ThatOneGuy42: I screwed up the page's formatting, fixed errors in the actual page, modified the phrasing of certain things, and occasionally actively reverted a previous change... and pull requests display all 'new' commits regardless of their substance, and regardless of whether they happened before or after the PR was made.

It happened last time I made a pull request, too. (Er, there weren't as many extra commits, but...) It's just as annoying for me as it might be for you. Heh. Sorry about that. I'm just... still getting used to this system.

**Comment by mustafakalash** [comment]
*Please* squash this.

**Comment by tlc2013** [comment]
I'll be honest about that: I looked up how to do that a long time ago and I couldn't figure it out for the life of me, even after I installed Git. I'm sorry, but I'm probably not going to be able to do that myself.

**Comment by samo-novak** [comment]
You can copy this file somwhere, close the PR, revert changes. Then you copy the file stored elsewhere back to your clone of the repository (really just copy it back where you took it from). Commit changes and create a new PR. That will put ALL your changes into that one commit.
@tlc2013

**Comment by samo-novak** [comment]
@tlc2013 You said you needed help, so I squashed it into one file for you, hope that's not a problem ;)

**Comment by Spookerton** [comment]
After some discussion on this topic, staff feedback has been universally in the negative about codifying prometheans as a race and, although the writing standard is decent, the content itself has had a pretty similar negative response. Based on that, I'm going to have to decline to include this material. Sorry a decision on the topic from the staff took so long.

**Pull request closed without merging**
