### PR TITLE
Harr'qac politics expansion

### PR DESCRIPTION
**Pull request by samo-novak**
Expansion on the politics and foreign relations of Harr'qac.

Tagging @ParadoxonKomplikon to look over it.

Also, please tell me if the government part is clear enough, I've been trying to make it more so lately.

### CODE REVIEW

**Comment by ParadoxonKomplikon** [comment]
Seems good enough to me.

**Comment by SubatomicTeddybear** [comment]
Assuming @ParadoxonKomplikon is the species master, I'll merge this hoe.

@Superbee29 Pls squash tho

**Comment by samo-novak** [comment]
I can try, but I think it can also be done in the target repository (this one). I'm not sure how, but #96 and #97 contained multiple commits, but were merged as one. @Spookerton probably murdered a unicorn to get that result... 

Anyway, I'm going to try to perform a proper ~blood magic ritual~ squash, hopefully it works.

**Comment by samo-novak** [comment]
Sacrificing blood, **DNM**

**Comment by samo-novak** [comment]
I gave up. Continuation of this is here: #104. I tried squashing, but due to having merged upstream into my repo, it was just too messed up. 
Anyway, please just look at the new PR.

**Pull request closed without merging**
