### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by samo-novak**
Formatting of hyphenation and headings. More formatting to come

### CODE REVIEW

**Comment by SubatomicTeddybear** [comment]
[Formatting intensifies]

**Comment by samo-novak** [comment]
Seriously though. Okay, you may call the typography thing (hyphen spacing, etc.) nitpicking, but we also have quite a lot of dysfunctional headers that needed to be fixed.

**Comment by ThatOneGuy42** [comment]
An issue I've noticed is that there has been differences between how the formatting works on the repo, and how it looks on the actual page.

**Comment by samo-novak** [comment]
You're right, the headings seem to work on the wiki. Apparently, it's more permissive than GitHub.
So, what do we do? I think the headers are now more of a policy discussion than a technical problem, since they work.

**Comment by samo-novak** [comment]
So, I can probably shelve that little script for headings... it had a good run XD

Anyway, there are still those space-hyphen-space edits that would not hurt if merged.

More importantly, there are those headings that include a part of the text, and it also displays on the wiki (see Unathi Clans). Those are also fixed by this PR.
pic

**Comment by SiegDerMaus** [comment]
Don't know if me still being able to merge here is an oversight or if I'm meant to be due to staying on as a lore assistant. But this has been open too long.

**Comment by samo-novak** [comment]
Thanks @SiegDerMaus

**Pull request merged**
