### PR TITLE
Adds Sol Gov Flag

### PR DESCRIPTION
**Pull request by ThatOneGuy42**
So redstryker made this I wanted to go ahead and get it up here and also I still have perms but I didnt want to be a dick and just straight up add it.

### CODE REVIEW

**Comment by redstryker** [comment]
(Add it, I was being a shit)

**Comment by ghost** [comment]
I'd recommend rehosting it on imgur myself, but that's personal not important.

**Comment by redstryker** [comment]
I don't know if Discord links expire.  I would recommend the same.  Or, just put it on the lore repo and link it directly.

**Comment by Raptor1628** [comment]
Either way :+1:

**Pull request merged**
