### PR TITLE
Resomii and other shit

### PR DESCRIPTION
**Pull request by Raptor1628**
Too much crap to list everything, but what I remember:

-Updates Resomii
-Adds Resomi colonies
-Touches up some Khaarmani removal stuff
-Adds templates
-A ton of other stuff

### CODE REVIEW

**Comment by Raptor1628** [comment]
This could use a squash from whoever merges it if that someone isn't me.

(If this is future raptor reading this, figure out how to squash from that end)

**Comment by MistakeNot4892** [comment]
```
git fetch upstream
git rebase -i upstream/master
set all 'pick' to 's' or 'squash' other than the very first commit
```

**Comment by Kasuobes** [comment]
`git merge master~77`

**Comment by Raptor1628** [comment]
For reference, it wasn't that I didn't know how, it's that the lore github has never worked on my desktop.

**Pull request merged**
