### PR TITLE
Changes Phoenix

### PR DESCRIPTION
**Pull request by Raptor1628**
FIRST PR!!!!!!!! _dank airhorns_

### CODE REVIEW

**Comment by ThatOneGuy42** [comment]
Theres a few more entries of Phoenix in the little article could you change
those too

**Comment by Raptor1628** [comment]
Shit -_- brought down by my own hubris. I'll change it in the morning.

**Comment by Peliia** [comment]
A small tip! You can take the source code, copy it into a Notepad(plus), and then use the Replace function, it then does the thing in header, body, everywhere! Then you just copy paste it back into the editor.

The only thing to watch out for is if the word you replace the thing with ends with 's' while original does not and vice versa, as that can result in grammar errors when used adjectively (ish, it's not exactly incorrect, but horrible styling), to counteract this two runs of Find and Replace have to be done, once with the apostrophed variant, and once without it (not in reverse order)

**Comment by Raptor1628** [comment]
I was actually just lazy and did it in the web client...

**Comment by Peliia** [comment]
I thought you may have, but any Windows has Notepad in it and that is just enough for you to paste it in there and then cut and paste it back into the web client :)

**Pull request merged**
