### PR TITLE
Removes Zzarlaanis

### PR DESCRIPTION
**Pull request by ghost**
It's... distressingly racist.   As discussed on the #lore channel on Discord.

### CODE REVIEW

**Comment by SiegDerMaus** [comment]
So, stereotypical Africa in space?

**Comment by Raptor1628** [comment]
There needs to be a concerted effort to remove and rework the many bad colonies in the lore.

**Comment by Raptor1628** [comment]
(Whoops, wrong button)

**Comment by ghost** [comment]
Probably.  This was just an egregious example of bad colony lore.

**Comment by SiegDerMaus** [comment]
Personally, I prefer improving over removing. But this is kinda bad.

**Comment by Raptor1628** [comment]
Could always set up a colony project on the forums, giving out colonies to improve and bring into compliance with the lore.

**Comment by SiegDerMaus** [comment]
This is true.

**Comment by SiegDerMaus** [comment]
I'd like for a rewrite to be at least attempted. Even if it becomes an almost completely different colony.

**Comment by SiegDerMaus** [comment]
@SkyMarshal , please try to come up with something to replace this. But since something this egregious has to go now.

**Pull request merged**
