### PR TITLE
Ports Dionaea wiki page

### PR DESCRIPTION
**Pull request by mustafakalash**
This is a direct port of the dionaea page from the mechanics wiki, on behalf of Noble

### CODE REVIEW

**Comment by ThatOneGuy42** [comment]
Fuck I forgot about this. Should make the necessary edits on the appropriate section page (I believe Section 1) so that it's accessible too.

**Comment by mustafakalash** [comment]
The section page already has a link. It should point to where I've put the file.

**Comment by Raptor1628** [comment]
@NobleCaos You're the dionaea master now right?

**Comment by SubatomicTeddybear** [comment]
Yes, I am the Lorax and I speak for the sentient trees.

Mvh Carl Oscar Nagell

**Comment by Raptor1628** [comment]
Alright then Noble, how does this look to you?

**Comment by SubatomicTeddybear** [comment]
This seems to be the wiki, so why would I be against it?

**Comment by Raptor1628** [comment]
Sometimes the Wiki pages were fairly out of date, just making sure nothing was a red flag.

**Comment by SubatomicTeddybear** [comment]
It has the stuff that I updated last night-ish. It's fine

Mvh Carl Oscar Nagell

**Comment by mustafakalash** [comment]
The idea was to port and then idea just for sanity.

**Comment by Raptor1628** [comment]
Rog, good to go then.

**Pull request merged**
